/**
 * Pre-renders every phrase the app can ever speak into a bundled MP3, using
 * ElevenLabs, and writes a manifest mapping exact text -> require()'d asset.
 * Run once (and again whenever workouts.json changes): the app then plays
 * these bundled files at runtime with no network call and no embedded key.
 *
 * Usage:
 *   ELEVENLABS_API_KEY=xxxx npx tsx scripts/generateTtsAssets.ts
 *   npx tsx scripts/generateTtsAssets.ts --dry-run   (no key needed, no API calls)
 *
 * The key can also be dropped in a gitignored .secrets/elevenlabs.key file
 * instead of passed as an env var.
 */
import * as fs from 'fs';
import * as path from 'path';
import { getAllAnnouncementTexts } from '../src/utils/workoutAnnouncements';

const VOICE_ID = process.env.ELEVENLABS_VOICE_ID || 'pNInz6obpgDQGcFmaJgB'; // "Adam" — warm, natural male voice
const MODEL_ID = 'eleven_turbo_v2_5';
const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'tts');
const MANIFEST_PATH = path.join(ROOT, 'src', 'utils', 'ttsManifest.generated.ts');
const KEY_FILE = path.join(ROOT, '.secrets', 'elevenlabs.key');

function loadApiKey(): string | undefined {
  if (process.env.ELEVENLABS_API_KEY) return process.env.ELEVENLABS_API_KEY.trim();
  if (fs.existsSync(KEY_FILE)) return fs.readFileSync(KEY_FILE, 'utf8').trim();
  return undefined;
}

function hashText(key: string): string {
  let hash = 0;
  for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) | 0;
  return String(Math.abs(hash));
}

async function main() {
  const texts = getAllAnnouncementTexts();
  const totalChars = texts.reduce((sum, t) => sum + t.length, 0);
  console.log(`Found ${texts.length} unique phrases, ${totalChars} total characters.`);

  const apiKey = loadApiKey();
  const dryRun = process.argv.includes('--dry-run') || !apiKey;

  if (dryRun) {
    console.log(apiKey
      ? '\n--dry-run passed — listing phrases without calling the API:\n'
      : '\nNo ELEVENLABS_API_KEY found (env var or .secrets/elevenlabs.key) — dry run only:\n');
    for (const t of texts.slice().sort()) console.log(' -', t);
    return;
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  let generated = 0;
  let cached = 0;
  let failed = 0;

  for (const text of texts) {
    const key = hashText(text);
    const filePath = path.join(OUT_DIR, `${key}.mp3`);
    if (fs.existsSync(filePath)) {
      cached++;
      continue;
    }
    try {
      const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Accept: 'audio/mpeg',
          'xi-api-key': apiKey!,
        },
        body: JSON.stringify({
          text,
          model_id: MODEL_ID,
          voice_settings: { stability: 0.55, similarity_boost: 0.8, style: 0.3, use_speaker_boost: true },
        }),
      });
      if (!res.ok) {
        failed++;
        console.error(`FAILED (${res.status}) for "${text}": ${await res.text()}`);
        continue;
      }
      const buffer = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(filePath, buffer);
      generated++;
      console.log(`Generated: ${text}`);
    } catch (e) {
      failed++;
      console.error(`FAILED for "${text}":`, e);
    }
  }

  const manifestLines = [
    '// AUTO-GENERATED by scripts/generateTtsAssets.ts — do not edit by hand.',
    '// Maps exact announcement text to its pre-rendered, bundled audio asset.',
    '// Re-run the script (see its header comment) after changing workouts.json.',
    'export const TTS_MANIFEST: Record<string, number> = {',
    ...texts.map(text => `  ${JSON.stringify(text)}: require('../../assets/tts/${hashText(text)}.mp3'),`),
    '};',
  ];
  fs.writeFileSync(MANIFEST_PATH, manifestLines.join('\n') + '\n');

  console.log(`\nDone. ${generated} generated, ${cached} already cached, ${failed} failed, ${texts.length} total.`);
  console.log(`Manifest written to ${path.relative(ROOT, MANIFEST_PATH)}`);
  if (failed > 0) process.exitCode = 1;
}

main().catch(e => {
  console.error(e);
  process.exitCode = 1;
});
